### ISSUE TITLE
Native AMD GPU support

### ISSUE THREAD

**Issue by dmikushin** [milancimbaljevic/llama.cpp#1]
# AMD backend for LLAMA.C++

This project is concentrated on enabling native AMD backend for LLAMA.C++, addressing the issues described below.

* The topmost and most annoying problem is the AMD's constant lag of support of their own hardware. The HPC software support of AMD GPUs is usually 1-2 generations behind the current. For example, given that gfx1100 series are being actively sold beginning of 2023, math libraries are barely supporting gfx103x series.

* LLAMA.C++ for GPUs comes with either CUBLAS (for NVIDIA), or CLBlast - for all the rest. CLBlast is based on OpenCL, meaning that it provides universal support across variety of OpenCL platforms. Focusing more on portability than on performance, OpenCL by its nature is often unable to generate the code, which efficiently leverages all features of the underlying architecture. Therefore, a native GPU support for AMD GPUs is desired, in order to offer performance on-par with NVIDIA CUBLAS.

## Preliminary proposal

Given that rocBLAS does not support modern AMD GPUs, we need to find an alternative. Maybe  [MAGMA](https://github.com/icl-utk-edu/magma) could be a fit?

## TODO list

- [ ] Review llama.cpp issues and PRs and identify relevant work and discussions, make notes of solutions and difficulties developers are running into
- [ ] Identify the scope of work: create a list of linear algebra functions that are needed to be provided, emphasizing on the data types
- [ ] Check required functions availability in MAGMA. Could functions with missing data types be created similarly to their equivalents for other data types?
